#!/usr/bin/env python3
"""Convert the Lucide SVGs in package/contents/icons/ui/ into one SVG path
string per icon (package/contents/code/Icons.js), so QML can draw them as
Shapes: tinted by strokeColor, crisp at any size, no shader needed.

    python3 tools/lucide-to-js.py
"""

import glob
import os
import re
import xml.etree.ElementTree as ET

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "package", "contents", "icons", "ui")
OUT = os.path.join(HERE, "..", "package", "contents", "code", "Icons.js")


def f(v, default=0.0):
    return float(v) if v not in (None, "") else default


NUM = re.compile(r"[-+]?(?:\d*\.\d+|\d+\.?)(?:[eE][-+]?\d+)?")


def absolute_start(d):
    """A path's leading `m` is absolute in SVG, but not once several elements
    are joined into one path string. Rewrite `m x y rest` as `M x y l rest`
    (implicit pairs after the first stay relative line-tos)."""
    d = d.strip()
    if not d.startswith("m"):
        return d
    body = d[1:]
    nums = list(NUM.finditer(body))
    if len(nums) < 2:
        return d
    x, y = nums[0].group(), nums[1].group()
    rest = body[nums[1].end() :].lstrip(" ,")
    if rest and (rest[0].isdigit() or rest[0] in "-+."):
        rest = "l" + rest
    return f"M{x} {y}" + rest


def to_path(el):
    tag = el.tag.split("}")[-1]
    a = el.attrib
    if tag == "path":
        return absolute_start(a["d"])
    if tag == "line":
        return f"M{a['x1']} {a['y1']}L{a['x2']} {a['y2']}"
    if tag in ("polyline", "polygon"):
        pts = a["points"].replace(",", " ").split()
        pairs = [f"{pts[i]} {pts[i + 1]}" for i in range(0, len(pts), 2)]
        return "M" + "L".join(pairs) + ("Z" if tag == "polygon" else "")
    if tag in ("circle", "ellipse"):
        cx, cy = f(a.get("cx")), f(a.get("cy"))
        rx = f(a.get("r", a.get("rx")))
        ry = f(a.get("r", a.get("ry")))
        return f"M{cx - rx} {cy}a{rx} {ry} 0 1 0 {2 * rx} 0a{rx} {ry} 0 1 0 {-2 * rx} 0"
    if tag == "rect":
        x, y, w, h = f(a.get("x")), f(a.get("y")), f(a["width"]), f(a["height"])
        r = min(f(a.get("rx", a.get("ry"))), w / 2, h / 2)
        if r == 0:
            return f"M{x} {y}h{w}v{h}h{-w}Z"
        return (
            f"M{x + r} {y}h{w - 2 * r}a{r} {r} 0 0 1 {r} {r}v{h - 2 * r}a{r} {r} 0 0 1 {-r} {r}"
            f"h{-(w - 2 * r)}a{r} {r} 0 0 1 {-r} {-r}v{-(h - 2 * r)}a{r} {r} 0 0 1 {r} {-r}Z"
        )
    raise ValueError(f"unsupported element {tag}")


def main():
    icons = {}
    for svg in sorted(glob.glob(os.path.join(SRC, "*.svg"))):
        root = ET.parse(svg).getroot()
        parts = [to_path(el) for el in root.iter() if el is not root]
        icons[os.path.basename(svg)[:-4]] = " ".join(parts)
    lines = [
        "// Generated by tools/lucide-to-js.py from icons/ui/*.svg — do not edit.",
        "// Lucide icons (ISC, see icons/ui/LICENSE-lucide.txt): 24×24, stroke 2, round caps.",
        ".pragma library",
        "",
        "var PATHS = {",
    ]
    lines += [f'    "{k}": "{v}",' for k, v in icons.items()]
    lines += ["};", ""]
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print(f"wrote {len(icons)} icons to {os.path.relpath(OUT)}")


if __name__ == "__main__":
    main()
